/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Controller.khachthueController;



/**
 *
 * @author Admin
 */
public class khachthueView extends javax.swing.JPanel {
    private khachthueController controller;
    // THÊM ĐÚNG DÒNG NÀY VÀO ĐÂY:
    private com.toedter.calendar.JDateChooser dtngaysinh = new com.toedter.calendar.JDateChooser();
    public khachthueView() {
        initComponents();
        controller = new khachthueController(this);
        getDateChooser().setMaxSelectableDate(new java.util.Date());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // --- CÁC HÀM GETTER ĐỂ CONTROLLER LẤY DỮ LIỆU ---

// Lấy ô nhập Họ tên
    public javax.swing.JTextField getTxtHoTen() { 
        return txthoten; 
    }

    // Lấy ô nhập CCCD
    public javax.swing.JTextField getTxtCCCD() { 
        return txtcccd; 
    }

    // Lấy ô nhập Số điện thoại
    public javax.swing.JTextField getTxtSDT() { 
        return txtdienthoai;
    }

    // Lấy ComboBox Giới tính
    public javax.swing.JComboBox<String> getCbGioiTinh() {
        return cbogioitinh; 
    }

    // QUAN TRỌNG: Lấy cái lịch JDateChooser
    public com.toedter.calendar.JDateChooser getDateChooser() {
        return dtngaysinh; 
    }

    // Lấy ô nhập Quê quán
    public javax.swing.JTextField getTxtQueQuan() { 
        return txtquequan; 
    }

    // Lấy cái bảng Table để đổ dữ liệu
    public javax.swing.JTable getTable() { 
        return tblkhachthue; 
    }
    
    public javax.swing.JTextField getTxtTimKiem() { 
        return txttk; 
    }


// --- HÀM MAIN ĐỂ CHẠY THỬ (Giống mẫu mày gửi) ---
public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> {
        javax.swing.JFrame frame = new javax.swing.JFrame("Quản Lý Khách Thuê");
        khachthueView view = new khachthueView();
        
        // Khởi tạo controller và kết nối với view này
        // new KhachThueController(view); 

        frame.add(view);
        frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    });
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        txtquequan = new javax.swing.JTextField();
        txtcccd = new javax.swing.JTextField();
        txtdienthoai = new javax.swing.JTextField();
        cbogioitinh = new javax.swing.JComboBox<>();
        txttk = new javax.swing.JTextField();
        khachthue = new javax.swing.JScrollPane();
        tblkhachthue = new javax.swing.JTable();
        btntk = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnmoi = new javax.swing.JButton();

        jLabel1.setText("Họ tên:");

        jLabel2.setText("CCCD:");

        jLabel3.setText("Giới tính:");

        jLabel4.setText("Điện thoại:");

        jLabel5.setText("Ngày sinh:");

        jLabel6.setText("Quê quán:");

        cbogioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        tblkhachthue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã khách", "Họ tên", "CCCD", "Điện thoại", "Giới tính", "Ngày sinh", "Quê quán"
            }
        ));
        tblkhachthue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblkhachthueMouseClicked(evt);
            }
        });
        khachthue.setViewportView(tblkhachthue);

        btntk.setText("Tìm kiếm");
        btntk.addActionListener(this::btntkActionPerformed);

        btnthem.setText("Thêm");
        btnthem.addActionListener(this::btnthemActionPerformed);

        btnsua.setText("Sửa");
        btnsua.addActionListener(this::btnsuaActionPerformed);

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(this::btnxoaActionPerformed);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Khách thuê");

        btnmoi.setText("Làm mới");
        btnmoi.addActionListener(this::btnmoiActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(khachthue, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(txttk, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btntk)
                        .addGap(30, 30, 30)
                        .addComponent(btnthem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdienthoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtcccd, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnsua)
                                    .addGap(34, 34, 34)
                                    .addComponent(btnxoa)
                                    .addGap(35, 35, 35)
                                    .addComponent(btnmoi))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6))
                                    .addGap(44, 44, 44)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbogioitinh, 0, 202, Short.MAX_VALUE)
                                        .addComponent(txtquequan))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntk, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmoi)
                    .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbogioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtcccd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(txtdienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtquequan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(khachthue, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btntkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntkActionPerformed
        controller.timKiem();   // TODO add your handling code here:
    }//GEN-LAST:event_btntkActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        controller.add();        // TODO add your handling code here:
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        controller.edit();// TODO add your handling code here:
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        controller.delete();        // TODO add your handling code here:
    }//GEN-LAST:event_btnxoaActionPerformed

    private void tblkhachthueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkhachthueMouseClicked
        controller.hienThiChiTiet();        // TODO add your handling code here:
    }//GEN-LAST:event_tblkhachthueMouseClicked

    private void btnmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoiActionPerformed
        controller.lamMoi();        // TODO add your handling code here:
    }//GEN-LAST:event_btnmoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmoi;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntk;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbogioitinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane khachthue;
    private javax.swing.JTable tblkhachthue;
    private javax.swing.JTextField txtcccd;
    private javax.swing.JTextField txtdienthoai;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtquequan;
    private javax.swing.JTextField txttk;
    // End of variables declaration//GEN-END:variables
}