/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;

/**
 *
 * @author Quang Huy
 */
public class MainForm extends javax.swing.JFrame {
    private JTabbedPane tabbedPane;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainForm.class.getName());

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        initMenuActions();
        showHome();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenuContainer = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnQLTTCS = new javax.swing.JButton();
        btnQLPT = new javax.swing.JButton();
        btnKHHD = new javax.swing.JButton();
        btnQuanLyHoaDon = new javax.swing.JButton();
        btnBaoCao = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainContentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMenuContainer.setLayout(new java.awt.BorderLayout());

        pnlMenu.setBackground(new java.awt.Color(34, 45, 80));
        pnlMenu.setMinimumSize(new java.awt.Dimension(250, 0));
        pnlMenu.setLayout(new java.awt.GridLayout(7, 1, 0, 5));

        jButton1.setBackground(new java.awt.Color(34, 45, 80));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Trang chủ");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 30, 10, 0));
        jButton1.setFocusPainted(false);
        jButton1.setHideActionText(true);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setIconTextGap(15);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        pnlMenu.add(jButton1);

        btnQLTTCS.setBackground(new java.awt.Color(34, 45, 80));
        btnQLTTCS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQLTTCS.setForeground(new java.awt.Color(255, 255, 255));
        btnQLTTCS.setText("Quản lý TT cơ sở");
        btnQLTTCS.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 30, 10, 0));
        btnQLTTCS.setFocusPainted(false);
        btnQLTTCS.setHideActionText(true);
        btnQLTTCS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQLTTCS.setIconTextGap(15);
        btnQLTTCS.addActionListener(this::btnQLTTCSActionPerformed);
        pnlMenu.add(btnQLTTCS);

        btnQLPT.setBackground(new java.awt.Color(34, 45, 80));
        btnQLPT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQLPT.setForeground(new java.awt.Color(255, 255, 255));
        btnQLPT.setText("Quản lý phương tiện");
        btnQLPT.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 30, 10, 0));
        btnQLPT.setFocusPainted(false);
        btnQLPT.setHideActionText(true);
        btnQLPT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQLPT.setIconTextGap(15);
        btnQLPT.addActionListener(this::btnQLPTActionPerformed);
        pnlMenu.add(btnQLPT);

        btnKHHD.setBackground(new java.awt.Color(34, 45, 80));
        btnKHHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKHHD.setForeground(new java.awt.Color(255, 255, 255));
        btnKHHD.setText("Quản lý khách hàng và hợp đồng");
        btnKHHD.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 30, 10, 0));
        btnKHHD.setFocusPainted(false);
        btnKHHD.setHideActionText(true);
        btnKHHD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKHHD.setIconTextGap(15);
        btnKHHD.addActionListener(this::btnKHHDActionPerformed);
        pnlMenu.add(btnKHHD);

        btnQuanLyHoaDon.setBackground(new java.awt.Color(34, 45, 80));
        btnQuanLyHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuanLyHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyHoaDon.setText("Quản lý hóa đơn");
        btnQuanLyHoaDon.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 30, 10, 0));
        btnQuanLyHoaDon.setFocusPainted(false);
        btnQuanLyHoaDon.setHideActionText(true);
        btnQuanLyHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyHoaDon.setIconTextGap(15);
        btnQuanLyHoaDon.addActionListener(this::btnQuanLyHoaDonActionPerformed);
        pnlMenu.add(btnQuanLyHoaDon);

        btnBaoCao.setBackground(new java.awt.Color(34, 45, 80));
        btnBaoCao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBaoCao.setForeground(new java.awt.Color(255, 255, 255));
        btnBaoCao.setText("Báo cáo và hợp đồng");
        btnBaoCao.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 30, 10, 0));
        btnBaoCao.setFocusPainted(false);
        btnBaoCao.setHideActionText(true);
        btnBaoCao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBaoCao.setIconTextGap(15);
        btnBaoCao.addActionListener(this::btnBaoCaoActionPerformed);
        pnlMenu.add(btnBaoCao);

        jButton7.setBackground(new java.awt.Color(34, 45, 80));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Cài đặt");
        jButton7.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 30, 10, 0));
        jButton7.setFocusPainted(false);
        jButton7.setHideActionText(true);
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.setIconTextGap(15);
        jButton7.addActionListener(this::jButton7ActionPerformed);
        pnlMenu.add(jButton7);

        pnlMenuContainer.add(pnlMenu, java.awt.BorderLayout.LINE_START);

        getContentPane().add(pnlMenuContainer, java.awt.BorderLayout.LINE_START);

        pnlHeader.setBackground(new java.awt.Color(34, 45, 80));
        pnlHeader.setMinimumSize(new java.awt.Dimension(80, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUẢN LÝ PHÒNG TRỌ");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(567, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        mainContentPanel.setBackground(new java.awt.Color(214, 234, 248));

        javax.swing.GroupLayout mainContentPanelLayout = new javax.swing.GroupLayout(mainContentPanel);
        mainContentPanel.setLayout(mainContentPanelLayout);
        mainContentPanelLayout.setHorizontalGroup(
            mainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );
        mainContentPanelLayout.setVerticalGroup(
            mainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        getContentPane().add(mainContentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKHHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKHHDActionPerformed
        // TODO add your handling code here:
        safeShow("Quản lý khách hàng và hợp đồng", () -> showQuanLyKhachHangTabs());
        
    }//GEN-LAST:event_btnKHHDActionPerformed

    private void showQuanLyKhachHangTabs() {

    mainContentPanel.removeAll();
    mainContentPanel.setLayout(new BorderLayout());

    tabbedPane = new JTabbedPane();

    tabbedPane.addTab("Khách thuê", new khachthueView());
    tabbedPane.addTab("Hợp đồng", new hopdongView());
    

    mainContentPanel.add(tabbedPane, BorderLayout.CENTER);

    mainContentPanel.revalidate();
    mainContentPanel.repaint();
}
    private void btnQLPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLPTActionPerformed
    safeShow("Quản lý phương tiện", () -> {
    QLPT_Panel qlpt = new QLPT_Panel(); 
    
    // 2. Xóa hết các nội dung cũ đang hiển thị trên panel chính
    mainContentPanel.removeAll();
    
    // 3. Set Layout để form con full màn hình trong panel chính
    mainContentPanel.setLayout(new java.awt.BorderLayout());
    
    // 4. Thêm form QLPT vào panel chính
    mainContentPanel.add(qlpt, BorderLayout.CENTER);
    
    // 5. Cập nhật lại giao diện (quan trọng để nó hiển thị ngay lập tức)
    mainContentPanel.revalidate();
    mainContentPanel.repaint();        // TODO add your handling code here:
        // 1. Tạo đối tượng form QLPT (đây là cái JPanel bạn tạo ở Bước 1)
    });
    }//GEN-LAST:event_btnQLPTActionPerformed

    private void btnQuanLyHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyHoaDonActionPerformed
     safeShow("Quản lý hóa đơn", () -> showQuanLyHoaDonTabs());// TODO add your handling code here:
    }//GEN-LAST:event_btnQuanLyHoaDonActionPerformed

    private void btnQLTTCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTTCSActionPerformed
       safeShow("Quản lý thông tin cơ sở", () -> showQuanLyTTCSTabs());
    }//GEN-LAST:event_btnQLTTCSActionPerformed

    private void showQuanLyBaoCaoTabs() {

    mainContentPanel.removeAll();
    mainContentPanel.setLayout(new BorderLayout());

    tabbedPane = new JTabbedPane();

    tabbedPane.addTab("Báo cáo doanh thu", new baocaodoanhthu());
    tabbedPane.addTab("Báo cáo thống kê", new thongkephongView());
    tabbedPane.addTab("Quản lý và báo cáo sự cố", new quanlysucoView());
    

    mainContentPanel.add(tabbedPane, BorderLayout.CENTER);

    mainContentPanel.revalidate();
    mainContentPanel.repaint();
}
    private void btnBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaoCaoActionPerformed
        // TODO add your handling code here:
        safeShow("Báo cáo", () -> showQuanLyBaoCaoTabs());
    }//GEN-LAST:event_btnBaoCaoActionPerformed

    private void showQuanLyTTCSTabs() throws SQLException {

    mainContentPanel.removeAll();
    mainContentPanel.setLayout(new BorderLayout());

    tabbedPane = new JTabbedPane();

    tabbedPane.addTab("Danh sách phòng", new PhongPanel());
    tabbedPane.addTab("Loại phòng", new LoaiPhongPanel());
    
    tabbedPane.addTab("Tài sản", new TaiSanPanel1());

    mainContentPanel.add(tabbedPane, BorderLayout.CENTER);

    mainContentPanel.revalidate();
    mainContentPanel.repaint();
}
    private void showQuanLyHoaDonTabs() {

    mainContentPanel.removeAll();
    mainContentPanel.setLayout(new BorderLayout());

    tabbedPane = new JTabbedPane();

    tabbedPane.addTab("Đơn giá dịch vụ", new DonGiaDichVuPanel());
    tabbedPane.addTab("Chỉ số điện nước", new ChiSoDienNuocPanel());
    
    tabbedPane.addTab("Hóa đơn", new HoaDonPanel());

    mainContentPanel.add(tabbedPane, BorderLayout.CENTER);

    mainContentPanel.revalidate();
    mainContentPanel.repaint();
}

    private void initMenuActions() {
        mainContentPanel.setLayout(new BorderLayout());
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        safeShow("Trang chủ", () -> showHome());
    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        safeShow("Cài đặt", () -> showSettings());
    }

    private void showHome() {
        mainContentPanel.removeAll();
        mainContentPanel.setLayout(new BorderLayout());
        JLabel label = new JLabel("Chào mừng đến với hệ thống quản lý phòng trọ", SwingConstants.CENTER);
        label.setFont(new java.awt.Font("Segoe UI", 1, 22));
        label.setForeground(new Color(34, 45, 80));
        label.setBorder(BorderFactory.createEmptyBorder(40, 20, 40, 20));
        mainContentPanel.add(label, BorderLayout.CENTER);
        mainContentPanel.revalidate();
        mainContentPanel.repaint();
    }

    private void showSettings() {
        mainContentPanel.removeAll();
        mainContentPanel.setLayout(new BorderLayout());
        JLabel label = new JLabel("Chức năng cài đặt đang được phát triển", SwingConstants.CENTER);
        label.setFont(new java.awt.Font("Segoe UI", 1, 20));
        label.setForeground(new Color(34, 45, 80));
        mainContentPanel.add(label, BorderLayout.CENTER);
        mainContentPanel.revalidate();
        mainContentPanel.repaint();
    }

    private void safeShow(String featureName, ThrowingRunnable action) {
        try {
            action.run();
        } catch (Throwable ex) {
            logger.log(java.util.logging.Level.SEVERE, featureName, ex);
            JOptionPane.showMessageDialog(this,
                    "Không mở được chức năng " + featureName + ":\n" + ex.getMessage(),
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    @FunctionalInterface
    private interface ThrowingRunnable {
        void run() throws Exception;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
        UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf()); // Hoặc FlatDarkLaf nếu thích tối
    } catch (Exception ex) {
        System.err.println("Failed to initialize LaF");
    }
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaoCao;
    private javax.swing.JButton btnKHHD;
    private javax.swing.JButton btnQLPT;
    private javax.swing.JButton btnQLTTCS;
    private javax.swing.JButton btnQuanLyHoaDon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMenuContainer;
    // End of variables declaration//GEN-END:variables
}
