/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Controller.quanlysucoController;
import baocaothongke.model.quanlysucoModel;
import java.util.List;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Dell
 */
public class quanlysucoView extends javax.swing.JPanel {
    private quanlysucoController controller;
     //phải có dòng này thì dòng trên mới ko lỗi

 private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(baocaodoanhthu.class.getName());

    /**
     * Creates new form quanlysucoView
     */
    public quanlysucoView() {
        initComponents();
         controller = new quanlysucoController(this);
        // Khởi tạo controller và truyền chính 'this' (View này) vào
        //controller = new thController(this);
        
        // Gán sự kiện khi chọn Mã Phòng thì cập nhật Mã Tài Sản
        cbmaphong.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controller.loadComboTaiSan();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        cbmaphong = new javax.swing.JComboBox<>();
        txttimkiem = new javax.swing.JTextField();
        btntimkiem = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbmataisan = new javax.swing.JComboBox<>();
        cbtrangthaixuly = new javax.swing.JComboBox<>();
        txtmasuco = new javax.swing.JTextField();
        txtmotasuco = new javax.swing.JTextField();
        txtchiphi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbsuco = new javax.swing.JTable();
        jSpinnerngaybao = new javax.swing.JSpinner();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Quản lý sự cố");

        btntimkiem.setBackground(new java.awt.Color(230, 229, 229));
        btntimkiem.setText("Tìm kiếm");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        btnthem.setBackground(new java.awt.Color(224, 223, 223));
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setBackground(new java.awt.Color(231, 226, 226));
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setBackground(new java.awt.Color(225, 223, 223));
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnreset.setBackground(new java.awt.Color(227, 227, 227));
        btnreset.setText("reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã sự cố");

        jLabel2.setText("Mã tài sản");

        jLabel3.setText("Trạng thái");

        jLabel6.setText("Ngày báo");

        jLabel7.setText("Mã phòng");

        jLabel9.setText("Chi phí dự kiến ");

        jLabel10.setText("Mô tả sự cố");

        cbtrangthaixuly.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "đã sửa", "chưa sửa", "chờ sửa", " " }));

        tbsuco.setBackground(new java.awt.Color(204, 204, 204));
        tbsuco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sự cố", "Mã tài sản", "Mã phòng", "Ngày báo", "Mô tả sự cố", "Trạng thái", "Chi phí"
            }
        ));
        tbsuco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbsucoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbsuco);

        jSpinnerngaybao.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbmaphong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbmataisan, 0, 185, Short.MAX_VALUE)
                    .addComponent(txtmasuco)
                    .addComponent(txtmotasuco))
                .addGap(6, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbtrangthaixuly, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtchiphi, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSpinnerngaybao))
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsua)
                    .addComponent(btnxoa)
                    .addComponent(btnthem))
                .addGap(340, 340, 340))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btntimkiem)
                        .addGap(66, 66, 66)
                        .addComponent(btnreset))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1014, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntimkiem)
                    .addComponent(btnreset))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(btnthem)))
                            .addComponent(txtmasuco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerngaybao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(cbmaphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbtrangthaixuly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(cbmataisan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(txtchiphi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnsua)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtmotasuco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnxoa)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
//
    // --- CÁC HÀM GETTER ĐỂ CONTROLLER TRUY XUẤT ---
    public JTextField getMaSC() { return txtmasuco;}
    public JComboBox<String> getMaPhong() { return cbmaphong; }
    public JComboBox<String> getMaTS() { return cbmataisan; }
    public java.util.Date getNgayBao() { 
    return (java.util.Date) jSpinnerngaybao.getValue(); 
}
    public JTextField getMoTa() { return txtmotasuco; }
    public JComboBox<String> getTrangThai() { return cbtrangthaixuly; }
    public JTextField getChiPhi() { return txtchiphi; }
    public JTable getTbSuCo() { return tbsuco; }
    public JTextField getTimKiem() { return txttimkiem; }
    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        controller.suaSuCo();
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        controller.themSuCo();
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        controller.xoaSuCo();
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
        // TODO add your handling code here:
        controller.timKiem();
    }//GEN-LAST:event_btntimkiemActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        controller.reset();
    }//GEN-LAST:event_btnresetActionPerformed

    private void tbsucoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbsucoMouseClicked
        // TODO add your handling code here:
        int row = tbsuco.getSelectedRow();
    if (row >= 0) {
        // --- 1. Đổ các ô văn bản ---
        txtmasuco.setText(tbsuco.getValueAt(row, 0).toString());
        txtmotasuco.setText(tbsuco.getValueAt(row, 4).toString());
        txtchiphi.setText(tbsuco.getValueAt(row, 6).toString());

        // --- 2. Đổ Mã Phòng (Cột 2) ---
        cbmaphong.setSelectedItem(tbsuco.getValueAt(row, 2).toString());

        // --- 3. Đổ Mã Tài Sản (Cột 1) ---
        // Lưu ý: Nếu Mã tài sản trong Combo là Object hoặc Số, ta dùng setSelectedItem
        String maTS = tbsuco.getValueAt(row, 1).toString();
        cbmataisan.setSelectedItem(maTS);

        // --- 4. Đổ Trạng Thái (Cột 5) ---
        // Thêm .trim() để xóa khoảng trắng thừa và ép về chữ thường nếu cần
        String trangThai = tbsuco.getValueAt(row, 5).toString().trim();
        cbtrangthaixuly.setSelectedItem(trangThai);

        // --- 5. Đổ Ngày Báo (Cột 3) ---
        Object ngayObj = tbsuco.getValueAt(row, 3);
        if (ngayObj != null) {
            jSpinnerngaybao.setValue(ngayObj);
        }
        
        txtmasuco.setEditable(false); // Khóa mã khi đang sửa
    }
    }//GEN-LAST:event_tbsucoMouseClicked


    public void clearForm() {
       txtmasuco.setText("");
    // Mở khóa lại ô mã sự cố để có thể nhập mới
    txtmasuco.setEditable(true); 
    
    // Đặt lại ngày hiện tại cho JSpinner
    jSpinnerngaybao.setValue(new java.util.Date());
    
    txtmotasuco.setText("");
    txtchiphi.setText("");
    
    // Reset các ComboBox
    if (cbmaphong.getItemCount() > 0) cbmaphong.setSelectedIndex(0);
    if (cbtrangthaixuly.getItemCount() > 0) cbtrangthaixuly.setSelectedIndex(0);
    
    // Đưa con trỏ chuột về ô mã để người dùng gõ luôn
    txtmasuco.requestFocus();
    }

    // --- HÀM HIỂN THỊ BẢNG ---
    public void hienThiBang(List<quanlysucoModel> list) {
        DefaultTableModel model = (DefaultTableModel) tbsuco.getModel();
        model.setRowCount(0);
        if (list != null) {
            for (quanlysucoModel sc : list) {
                Object[] row = {
                    sc.getMaSC(), 
                    sc.getMaTS(), 
                    sc.getMaPhong(),
                    sc.getNgayBao(), 
                    sc.getMoTa(), 
                    sc.getTrangThai(),
                    sc.getChiPhi()
                };
                model.addRow(row);
            }
        }
    }
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame("Kiểm tra giao diện Quản lý sự cố");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.add(new quanlysucoView());
                frame.pack();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbmaphong;
    private javax.swing.JComboBox<String> cbmataisan;
    private javax.swing.JComboBox<String> cbtrangthaixuly;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerngaybao;
    private javax.swing.JTable tbsuco;
    private javax.swing.JTextField txtchiphi;
    private javax.swing.JTextField txtmasuco;
    private javax.swing.JTextField txtmotasuco;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
